nodeLinker: node-modules

packageExtensions:
  "blues-stack-template@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@remix-run/dev@*":
    peerDependencies:
      "@babel/preset-env": "*"
      react: "*"
      react-dom: "*"
  "@remix-run/express@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/node@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
